language: php

php:
  - 5.4
  - 5.5
  - 5.6
  - hhvm
  - nightly

before_install:
  - composer self-update

install:
  - travis_retry composer install --no-interaction --prefer-source

script:
  - make deps
  - make cs
  - make test

after_script:
  - make coveralls
