language: php

php:
  - 5.6
  - 7.0
  - hhvm

matrix:
  allow_failures:
    - php: hhvm

before_install:
  - composer self-update

install:
  - travis_retry make deps

script:
  - make cs
  - make test

after_script:
  - make coveralls
